# Generated by Django 5.0.4 on 2024-04-22 20:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentdocument',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
